### ISSUE TITLE
[QUESTION] 스피너 너비를 선택한 텍스트의 너비로 설정하는 방법

### ISSUE THREAD

**Issue by b1urrrr** [SujungVillage/SujungVillage-Admin-Android#19]
스피너 너비가 텍스트 리스트 중 가장 글자수가 긴 텍스트의 너비로 설정되고 있어 😞
현재 선택한 텍스트의 너비로 스피너의 너비가 계속 바뀌었으면 좋겠는데 방법이 있을까?

예 ) "전체"가 선택됐을 때는 두 글자만큼 스피너가 짧아지고, "그레이스"가 선택됐을 때는 네 글자만큼 스피너가 길어졌으면 좋겠음

<br>

> ### 관련 파일들
> - activity_notice.xml
> - NoticeActivity.kt
> - spinner_notice_dormitory.xml

**Comment by flora7883** [comment]
나는 wrap content로 하긴 했는데 꼭 글자 수에 따라 바뀌어야해?

**Comment by b1urrrr** [comment]
> 나는 wrap content로 하긴 했는데 꼭 글자 수에 따라 바뀌어야해?

나도 일단 wrap content로 하는 중인데 이렇게 하니까 피그마 디자인이랑 조금 달라서 방법이 있다면 글자수에 맞게 바꾸고 싶어!

**Comment by b1urrrr** [comment]
어떻게 하다보니까 됐는데 오히려 이게 안 예쁜 것 같기도 하고... 한번 회의 때 말해봐야겠다
